import { spawn } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { Platform } from '../platform/platform.js';
import type { Logger } from '../utils/logger.js';
import { silentLogger } from '../utils/logger.js';
import { assetPath } from '../utils/paths.js';

export type SoundName = 'attention' | 'completion' | 'error';

export interface SoundPlayer {
  isAvailable(): boolean;
  play(sound: SoundName, volume?: number): Promise<void>;
}

export interface SoundServiceOptions {
  platform: Platform;
  logger?: Logger;
  /** Overridable so tests do not touch the filesystem or spawn processes. */
  resolveFile?: (sound: SoundName) => string;
  timeoutMs?: number;
}

const DEFAULT_TIMEOUT_MS = 5000;

export function defaultSoundFile(sound: SoundName): string {
  return assetPath('sounds', `${sound}.wav`);
}

/** Applies gain to the 16-bit PCM WAV assets generated by PingBack. */
export function scalePcm16Wave(source: Buffer, volume: number): Buffer {
  const adjusted = Buffer.from(source);
  if (
    adjusted.length < 44 ||
    adjusted.toString('ascii', 0, 4) !== 'RIFF' ||
    adjusted.toString('ascii', 8, 12) !== 'WAVE'
  ) {
    return adjusted;
  }

  let offset = 12;
  let isPcm16 = false;

  while (offset + 8 <= adjusted.length) {
    const id = adjusted.toString('ascii', offset, offset + 4);
    const size = adjusted.readUInt32LE(offset + 4);
    const dataOffset = offset + 8;
    const dataEnd = dataOffset + size;
    if (dataEnd > adjusted.length) return adjusted;

    if (id === 'fmt ' && size >= 16) {
      isPcm16 =
        adjusted.readUInt16LE(dataOffset) === 1 &&
        adjusted.readUInt16LE(dataOffset + 14) === 16;
    }

    if (id === 'data' && isPcm16) {
      for (let index = dataOffset; index + 1 < dataEnd; index += 2) {
        adjusted.writeInt16LE(Math.round(adjusted.readInt16LE(index) * volume), index);
      }
      return adjusted;
    }

    offset = dataEnd + (size % 2);
  }

  return adjusted;
}

/**
 * Plays a bundled WAV using the OS's built-in player.
 *
 * Playback failures are never fatal: a missing audio device must not stop the
 * desktop notification from being delivered.
 */
export class SoundService implements SoundPlayer {
  readonly #platform: Platform;
  readonly #logger: Logger;
  readonly #resolveFile: (sound: SoundName) => string;
  readonly #timeoutMs: number;

  constructor(options: SoundServiceOptions) {
    this.#platform = options.platform;
    this.#logger = options.logger ?? silentLogger();
    this.#resolveFile = options.resolveFile ?? defaultSoundFile;
    this.#timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  }

  isAvailable(): boolean {
    return existsSync(this.#resolveFile('attention'));
  }

  async play(sound: SoundName, volume: number = 1): Promise<void> {
    const file = this.#resolveFile(sound);

    if (!existsSync(file)) {
      this.#logger.warn('sound asset missing', { sound, file });
      return;
    }

    const playback = this.#preparePlaybackFile(file, volume);
    const { command, args } = this.#platform.buildSoundCommand(playback.file, volume);

    await new Promise<void>((resolve) => {
      let settled = false;
      const finish = (): void => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        playback.dispose();
        resolve();
      };

      const child = spawn(command, args, { stdio: 'ignore', windowsHide: true });

      const timer = setTimeout(() => {
        child.kill();
        this.#logger.warn('sound playback timed out', { sound });
        finish();
      }, this.#timeoutMs);

      child.once('error', (error) => {
        this.#logger.warn('sound playback failed', { sound, err: error });
        finish();
      });
      child.once('close', finish);
    });
  }

  #preparePlaybackFile(
    file: string,
    volume: number,
  ): { file: string; dispose: () => void } {
    if (this.#platform.id !== 'windows' || volume === 1) {
      return { file, dispose: () => undefined };
    }

    try {
      const directory = mkdtempSync(path.join(tmpdir(), 'pingback-sound-'));
      const scaledFile = path.join(directory, path.basename(file));
      writeFileSync(scaledFile, scalePcm16Wave(readFileSync(file), volume));
      return {
        file: scaledFile,
        dispose: () => {
          rmSync(directory, { recursive: true, force: true });
        },
      };
    } catch (error) {
      this.#logger.warn('sound volume preparation failed', { err: error });
      return { file, dispose: () => undefined };
    }
  }
}

/** Used when sound is disabled in config. */
export class NullSoundPlayer implements SoundPlayer {
  isAvailable(): boolean {
    return false;
  }

  play(_sound: SoundName, _volume?: number): Promise<void> {
    return Promise.resolve();
  }
}
